# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-11 21:39
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/images/', verbose_name='导航图')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '首页幻灯片',
                'verbose_name_plural': '首页幻灯片',
            },
        ),
        migrations.CreateModel(
            name='BannerAd1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='类目')),
                ('weight', models.IntegerField(default=1, verbose_name='权重')),
                ('status', models.BooleanField(default=1, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '类别管理',
                'verbose_name_plural': '类别管理',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/banner_images/', verbose_name='商品导图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标题')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='售价')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='原价')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='product/images/', verbose_name='封面图')),
                ('summary', DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='商品描述')),
                ('stock', models.IntegerField(default=0, verbose_name='库存量')),
                ('status', models.BooleanField(default=1, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.CategoryInfo', verbose_name='类目')),
            ],
            options={
                'verbose_name': '产品中心',
                'verbose_name_plural': '产品中心',
            },
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.ProductInfo', verbose_name='所属商品'),
        ),
        migrations.AddField(
            model_name='bannerad1',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductInfo', unique=True, verbose_name='所属商品'),
        ),
        migrations.AddField(
            model_name='bannerad',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductInfo', unique=True, verbose_name='所属商品'),
        ),
    ]
