# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='类目')),
                ('weight', models.IntegerField(default=1, verbose_name='权重')),
                ('status', models.BooleanField(default=1, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标题')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='售价')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='原价')),
                ('main_image', models.ImageField(upload_to='product/images/', verbose_name='封面图')),
                ('summary', models.TextField(blank=True, max_length=500, null=True, verbose_name='商品描述')),
                ('stock', models.IntegerField(default=0, verbose_name='库存量')),
                ('status', models.BooleanField(default=1, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.CategoryInfo', verbose_name='类目')),
            ],
        ),
    ]
