# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='名称')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='手机号码')),
                ('sex', models.IntegerField(choices=[(0, '未知'), (2, '女'), (1, '男')], default=0, verbose_name='性别')),
                ('avatar', models.CharField(max_length=200, verbose_name='头像')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
        ),
    ]
